functionsDirectory = "C:\\Users\\geral\\Documents\\Dev\\portfolio\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\geral\\Documents\\Dev\\portfolio\\public"
publishOrigin = "config"
functions = "C:\\Users\\geral\\Documents\\Dev\\portfolio\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]